### ISSUE TITLE
help theme not loading 

### ISSUE THREAD

**Issue by thrizy** [lovelle/jquery-chat#28]
pls i am new to git hub and i downloaded your jquery chat but the theme is not coming up its just plain i dont know if it has something to do with the ui

**Comment by lovelle** [comment]
Hello, I'll try to guess what is happening because there are not many details about the issue.
Take a look in root project folder there is a symbolic link called "themes" and points to  "jquery-ui-themes-1.10.4/themes/" and perhaps you put the chat behind an apache, you should have the directive "Options +FollowSymLinks" to allow symbolic links, or, you could copy the directory "jquery-ui-themes-1.10.4/themes/" to themes folder.

If this is the problem, you should have a log lines like this in error log of apache:
"Symbolic link not allowed or link target not accessible"

Hope this help you.
Bye

**Comment by thrizy** [comment]
the problem is the chat works fyn but seems like .css files is not being detected i mean the jquery ui theme the popup doesn't even work well 
![screenshot 19](https://cloud.githubusercontent.com/assets/10042811/9938086/8d1b9edc-5d5b-11e5-83ce-58715b8876fd.png)

i have posted an image of how it displays jquery ui theme is not responding

**Comment by thrizy** [comment]
s what do i do to make it look like the one i see on your demo

**Comment by thrizy** [comment]
thanks i solved it only one small problem when i run the application on my website i see so many people online even ehen no one is logged on 
why is this??

**Comment by thrizy** [comment]
then the images appended to the user during chat can i change it

**Comment by ferenczAndras** [comment]
Right now you are connected to the online already running server. You need to create your own server on Local machine in order not to see those. You need to implement the method, to change an avatar because at the moment for every user is automatically generated one.
Sorry If I say something wrong, I only want to help Mr. Lovelle :)

**Comment by ferenczAndras** [comment]
In order to make themes work, create a folder in the main folder and named it "themes", and put it in the themes folder all the folders from the "jquery-ui-themes-1.10.4/themes/" folder. This is the easiest way to do it.

**Comment by lovelle** [comment]
Hi, sorry for delay, @ferenczAndras Thank you very much for answer this issue, we are here for help each other much as we can, please feel free to do it in the future  :+1:

@thrizy  as @ferenczAndras said, by default you are connected with jqchat deployed on heroku, if you want your own server please take a look at step 3 in Readme.

**Comment by lovelle** [comment]
solved
