### ISSUE TITLE
.net intergration

### ISSUE THREAD

**Issue by davidbuckleyni** [lovelle/jquery-chat#30]
Can this be easy added to a .net page and how is the friend list and communication handled between user. Ie how do i send the firend list form sql server to ur script just a webservice?. What json is expected.

**Comment by lovelle** [comment]
Please excuse me, I was on vacation and I wasn't able to answer.

The answer is Yes, because the whole chat works by Javascript side, so, it doesn't matter what framework do you use.

The communication between the server and the client is handled thanks socket.io, for more information please see http://socket.io/.

The users online list is handled just by a variable stored in memory, of course, instead of using a variable in memory, this data could be stored in a database. This must be done in "server/node/server.js" or "server/python/server.py" depending on what server deploy do you decide to have.

The next is a example of how the users list works:

``` javascript
{
  'foo@foo.com': 
  {
    uid: 1,
    user: 'foo@foo.com',
    name: 'foo',
    status: 'online',
    avatar: 'http://www.gravatar.com/avatar/3717483f26171b61a4e2154fb37ffbd1/?d=retro'
  },
  'bar@bar.com': 
  {
    uid: 2,
    user: 'bar@bar.com',
    name: 'bar',
    status: 'online',
    avatar: 'http://www.gravatar.com/avatar/d73432634e2174d2ce30f3fdf9e445a4/?d=mm'
  } 
}
```

I hope this can help.

**Comment by lovelle** [comment]
Closed due to not activity
