### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by doggodoodle** [lovelle/jquery-chat#38]
Question 1: In installation instructions step2-Configuration, what needs to be added in index.html? I am not sure in what form the server info needs to be added in this step:
"And the same for line 11 in index.html
$ editor index.html"

Question 2: I skipped above step and tried to bring up jqchat using python server as explained in the instructions. But the chat window always shows “Disconnected”. What could I be missing? Can you please give pointers on where should I look at to fix this?

**Comment by lovelle** [comment]
Hi, the line specified in readme was wrong, Now is fixed.

Q1: This is telling you that you need to change that line in order to connect to your own socket.io server.
Q2: you are not connecting to server, open chrome debug console and see the real reason.

I've just testes and is working good.

Closing, the wrong doc was fixed.
Bye.
